In [2]:
import pandas as pd

In [3]:
train = pd.read_json("train.json")
test = pd.read_json("test.json")

In [4]:
train

,ner_tags,ner_ids,tokens,space_after
0,"[O, GPE, O, O, O, O, O, O, LOC, O, O, O, O, O,...","[0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, ...","[În, România, ,, ca, de, altfel, în, întreaga,...","[True, False, True, True, True, True, True, Tr..."
1,"[O, O, O, DATETIME, DATETIME, O, O, O, O, O, O...","[0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 13, 13, 1...","[Se, estimează, că, în, prezent, acestea, sunt...","[True, True, True, True, True, True, True, Tru..."
2,"[O, O, O, O, O, NUMERIC, O, O, O, PERSON, O, P...","[0, 0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 1, 0, 0, 1,...","[Cartea, cuprinde, o, suită, de, 115, texte-re...","[True, True, True, True, True, True, True, Tru..."
3,"[O, O, O, O, O, O, O, O, O, O, O, DATETIME, DA...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 0]","[Bursele, pentru, proiecte, ArtsLink, -, terme...","[True, True, True, True, True, True, True, Tru..."
4,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Aplicația, informațională, este, însoțită, de...","[True, True, True, True, True, True, True, Tru..."
...,...,...,...,...
12325,"[O, O, NUMERIC, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[În, Capitolul, IV, “, Rolul, unităților, de, ...","[True, True, True, False, True, True, True, Tr..."
12326,"[O, O, O, O, O, GPE, O, O, O, O, GPE, O, GPE, ...","[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 3, 0, 0, ...","[Naționala, de, volei, masculin, a, României, ...","[True, True, True, True, True, True, True, Fal..."
12327,"[PERSON, O, O, O, O, ORG, O, PERSON, PERSON, O...","[1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, ...","[Președintele, Comisiei, de, Buget, a, Senatul...","[True, True, True, True, True, False, True, Tr..."
12328,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Majorarea, este, justificată, de, benzinari, ...","[True, True, True, True, True, True, True, Tru..."
12329,"[O, O, O, PERSON, O, O, O, O, O, O, O, O, O, O...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Între, timp, ,, concubina, acestuia, și-, a, ...","[True, False, True, True, True, False, True, T..."

In [5]:
test

,tokens,space_after
0,"[Cazul, tinerei, agresate, de, agenții, de, pa...","[True, True, True, True, True, True, True, Fal..."
1,"[\n, Scandal, la, Carrefour, Braşov, :, Unde, ...","[False, True, True, True, False, True, True, T..."
2,"[De, ce, câștigă, Facebook, și, când, utilizat...","[True, True, True, True, True, True, True, Tru..."
3,"[EXCLUSIV, !, Tupeu, fără, margini, !, Profi, ...","[False, True, True, True, False, True, True, T..."
4,"[PROFI, ,, în, mijlocul, unui, scandal, !, Rep...","[False, True, True, True, True, False, True, T..."
...,...,...
2416,"[34,18, dolari, SUA, ,, voi, cumpăra, 5, mii, ...","[True, True, False, True, True, True, True, Tr..."
2417,"[$, RH, Interes, scurt, imens, ., Toate, vânză...","[True, True, True, True, False, True, True, Tr..."
2418,"[$, TVIX, în, @, 10,07, $, vă, rugăm, să, nu, ...","[True, True, True, True, True, True, True, Tru..."
2419,"[$, AAPL, piatră, de, mormânt, care, indică, o...","[True, True, True, True, True, True, True, Tru..."
2420,"[$, WY, supraevaluat, ...., îmi, pare, rău, ,,...","[True, True, True, True, True, True, False, Tr..."