In [268]:
import pandas as pd
import matplotlib.pyplot as plt

In [269]:
train = pd.read_csv("train_final.csv")
test = pd.read_csv("test_final.csv")
ids = test["row_id"]

In [270]:
train = train.sort_values("date", ascending=True)

In [271]:
train

,row_id,date,store_id,city,region,product_id,product_name,category,price,loyalty_day,is_holiday,holiday_name,demand
420500,0,2023-05-15,CM-BAC-01,Bacău,Moldova,P0001,Apă plată 2L,Beverages,4.51,0,0,NaN,3
420501,726,2023-05-15,CM-BAC-01,Bacău,Moldova,P0002,Apă minerală carbogazoasă 1.5L,Beverages,9.06,0,0,NaN,6
420502,1452,2023-05-15,CM-BAC-01,Bacău,Moldova,P0003,Cola 2L,Beverages,10.30,0,0,NaN,0
420503,2178,2023-05-15,CM-BAC-01,Bacău,Moldova,P0004,Suc natural portocale 1L,Beverages,8.65,0,0,NaN,1
420504,2904,2023-05-15,CM-BAC-01,Bacău,Moldova,P0005,Bere lager 0.5L,Beverages,4.51,0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,418175,2025-05-10,CM-TIM-01,Timișoara,Banat,P0054,Mălai 1kg,Pantry,14.63,1,0,NaN,1
576,418901,2025-05-10,CM-TIM-01,Timișoara,Banat,P0055,Joc puzzle mini,Toys & Games,10.73,1,0,NaN,0
577,419627,2025-05-10,CM-TIM-01,Timișoara,Banat,P0056,Bandă elastică fitness,Sports & Hobbies,55.49,1,0,NaN,0
578,420353,2025-05-10,CM-TIM-01,Timișoara,Banat,P0057,Lingură silicon 30cm,Home & Kitchen,9.86,1,0,NaN,2
579,421079,2025-05-10,CM-TIM-01,Timișoara,Banat,P0058,Cremă de mâini 75ml,Personal Care & Cleaning,15.11,1,0,NaN,1

In [272]:
import pandas as pd
import numpy as np

def prep(train, test):

    train = train.copy()
    test = test.copy()

    # --------------------------
    # DATE FEATURES
    # --------------------------
    for df in [train, test]:
        df["date"] = pd.to_datetime(df["date"])

        df["day"] = df["date"].dt.day
        df["month"] = df["date"].dt.month
        df["year"] = df["date"].dt.year
        df["dayofweek"] = df["date"].dt.dayofweek
        df["weekofyear"] = df["date"].dt.isocalendar().week.astype(int)

        df["is_weekend"] = (df["dayofweek"] >= 5).astype(int)

        start_date = pd.Timestamp("2023-01-01")
        df["days_since_2023"] = (df["date"] - start_date).dt.days

    # --------------------------
    # TARGET ENCODING FEATURES (FROM TRAIN ONLY)
    # --------------------------

    global_mean = train["demand"].mean()

    # product_id mean
    group_cols = [
        "product_id",
        "region",
        "city",
        "category",
        "store_id"
    ]
    
    means = {
        col: train.groupby(col)["demand"].mean()
        for col in group_cols
    }
    for col in group_cols:
        train[f"{col}_mean"] = train[col].map(means[col])
        test[f"{col}_mean"] = test[col].map(means[col])

        # fill missing (important for test unseen categories)
        global_mean = train["demand"].mean()

        train[f"{col}_mean"] = train[f"{col}_mean"].fillna(global_mean)
        test[f"{col}_mean"] = test[f"{col}_mean"].fillna(global_mean)


    # --------------------------
    # DROP UNUSED COLUMNS
    # --------------------------
    train = train.drop(columns=["date", "row_id"])
    test = test.drop(columns=["date", "row_id"])

    # --------------------------
    # ONE-HOT ENCODING
    # --------------------------
    full = pd.concat([train, test], axis=0)
    full = pd.get_dummies(full)

    train = full.iloc[:len(train)].copy()
    test = full.iloc[len(train):].copy()

    return train, test

In [273]:
train, test = prep(train, test)

In [274]:
X_train = train.drop(columns="demand")
y_train = train["demand"]
X_test = test.drop(columns="demand")

In [275]:
train

,price,loyalty_day,is_holiday,demand,day,month,year,dayofweek,weekofyear,is_weekend,...,holiday_name_Sf. Andrei,holiday_name_Sf. Maria,holiday_name_Sf. Nicolae,holiday_name_Sf. Valentin,holiday_name_Unirea Principatelor,holiday_name_Vinerea Mare,holiday_name_Ziua Copilului,holiday_name_Ziua Femeii,holiday_name_Ziua Muncii,holiday_name_Ziua Națională
420500,4.51,0,0,3.0,15,5,2023,0,20,0,...,False,False,False,False,False,False,False,False,False,False
420501,9.06,0,0,6.0,15,5,2023,0,20,0,...,False,False,False,False,False,False,False,False,False,False
420502,10.30,0,0,0.0,15,5,2023,0,20,0,...,False,False,False,False,False,False,False,False,False,False
420503,8.65,0,0,1.0,15,5,2023,0,20,0,...,False,False,False,False,False,False,False,False,False,False
420504,4.51,0,0,0.0,15,5,2023,0,20,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,14.63,1,0,1.0,10,5,2025,5,19,1,...,False,False,False,False,False,False,False,False,False,False
576,10.73,1,0,0.0,10,5,2025,5,19,1,...,False,False,False,False,False,False,False,False,False,False
577,55.49,1,0,0.0,10,5,2025,5,19,1,...,False,False,False,False,False,False,False,False,False,False
578,9.86,1,0,2.0,10,5,2025,5,19,1,...,False,False,False,False,False,False,False,False,False,False
579,15.11,1,0,1.0,10,5,2025,5,19,1,...,False,False,False,False,False,False,False,False,False,False

In [276]:
from catboost import CatBoostRegressor
from sklearn.svm import SVR

model = CatBoostRegressor(
    depth=8,
    learning_rate=0.03,
)

In [277]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, shuffle=False, test_size=0.2)

In [278]:
X_val

,price,loyalty_day,is_holiday,day,month,year,dayofweek,weekofyear,is_weekend,days_since_2023,...,holiday_name_Sf. Andrei,holiday_name_Sf. Maria,holiday_name_Sf. Nicolae,holiday_name_Sf. Valentin,holiday_name_Unirea Principatelor,holiday_name_Vinerea Mare,holiday_name_Ziua Copilului,holiday_name_Ziua Femeii,holiday_name_Ziua Muncii,holiday_name_Ziua Națională
84564,4.38,1,0,16,12,2024,0,51,0,715,...,False,False,False,False,False,False,False,False,False,False
84565,8.93,1,0,16,12,2024,0,51,0,715,...,False,False,False,False,False,False,False,False,False,False
84566,10.01,1,0,16,12,2024,0,51,0,715,...,False,False,False,False,False,False,False,False,False,False
84567,8.84,1,0,16,12,2024,0,51,0,715,...,False,False,False,False,False,False,False,False,False,False
84568,4.38,1,0,16,12,2024,0,51,0,715,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,14.63,1,0,10,5,2025,5,19,1,860,...,False,False,False,False,False,False,False,False,False,False
576,10.73,1,0,10,5,2025,5,19,1,860,...,False,False,False,False,False,False,False,False,False,False
577,55.49,1,0,10,5,2025,5,19,1,860,...,False,False,False,False,False,False,False,False,False,False
578,9.86,1,0,10,5,2025,5,19,1,860,...,False,False,False,False,False,False,False,False,False,False
579,15.11,1,0,10,5,2025,5,19,1,860,...,False,False,False,False,False,False,False,False,False,False

In [279]:
model.fit(X_train, y_train, eval_set=(X_val, y_val))

0:	learn: 2.7800127	test: 2.5600051	best: 2.5600051 (0)	total: 21.5ms	remaining: 21.5s
1:	learn: 2.7531162	test: 2.5414287	best: 2.5414287 (1)	total: 37.8ms	remaining: 18.9s
2:	learn: 2.7278906	test: 2.5280335	best: 2.5280335 (2)	total: 54.7ms	remaining: 18.2s
3:	learn: 2.7029386	test: 2.5132936	best: 2.5132936 (3)	total: 71.8ms	remaining: 17.9s
4:	learn: 2.6792445	test: 2.4965094	best: 2.4965094 (4)	total: 89ms	remaining: 17.7s
5:	learn: 2.6578360	test: 2.4803248	best: 2.4803248 (5)	total: 105ms	remaining: 17.3s
6:	learn: 2.6375394	test: 2.4659209	best: 2.4659209 (6)	total: 120ms	remaining: 17s
7:	learn: 2.6172269	test: 2.4524063	best: 2.4524063 (7)	total: 137ms	remaining: 17s
8:	learn: 2.5983722	test: 2.4383625	best: 2.4383625 (8)	total: 151ms	remaining: 16.7s
9:	learn: 2.5798364	test: 2.4272178	best: 2.4272178 (9)	total: 168ms	remaining: 16.6s
10:	learn: 2.5620779	test: 2.4192588	best: 2.4192588 (10)	total: 184ms	remaining: 16.6s
11:	learn: 2.5443954	test: 2.4151268	best: 2.4151268 (11)	total: 200ms	remaining: 16.5s
12:	learn: 2.5280019	test: 2.4060215	best: 2.4060215 (12)	total: 219ms	remaining: 16.6s
13:	learn: 2.5118028	test: 2.4009253	best: 2.4009253 (13)	total: 235ms	remaining: 16.6s
14:	learn: 2.4979345	test: 2.3922995	best: 2.3922995 (14)	total: 252ms	remaining: 16.6s
15:	learn: 2.4841974	test: 2.3848875	best: 2.3848875 (15)	total: 269ms	remaining: 16.5s
16:	learn: 2.4712066	test: 2.3787255	best: 2.3787255 (16)	total: 285ms	remaining: 16.5s
17:	learn: 2.4562256	test: 2.3678492	best: 2.3678492 (17)	total: 301ms	remaining: 16.4s
18:	learn: 2.4435783	test: 2.3596407	best: 2.3596407 (18)	total: 318ms	remaining: 16.4s
19:	learn: 2.4320370	test: 2.3529505	best: 2.3529505 (19)	total: 330ms	remaining: 16.2s
20:	learn: 2.4206562	test: 2.3500478	best: 2.3500478 (20)	total: 344ms	remaining: 16s
21:	learn: 2.4100294	test: 2.3421731	best: 2.3421731 (21)	total: 357ms	remaining: 15.9s
22:	learn: 2.3996058	test: 2.3343562	best: 2.3343562 (22)	total: 371ms	remaining: 15.8s
23:	learn: 2.3894010	test: 2.3275964	best: 2.3275964 (23)	total: 384ms	remaining: 15.6s
24:	learn: 2.3802316	test: 2.3220332	best: 2.3220332 (24)	total: 397ms	remaining: 15.5s
25:	learn: 2.3712791	test: 2.3164858	best: 2.3164858 (25)	total: 411ms	remaining: 15.4s
26:	learn: 2.3622760	test: 2.3101160	best: 2.3101160 (26)	total: 424ms	remaining: 15.3s
27:	learn: 2.3546024	test: 2.3048114	best: 2.3048114 (27)	total: 437ms	remaining: 15.2s
28:	learn: 2.3453521	test: 2.2991316	best: 2.2991316 (28)	total: 449ms	remaining: 15s
29:	learn: 2.3373701	test: 2.2994242	best: 2.2991316 (28)	total: 463ms	remaining: 15s
30:	learn: 2.3298146	test: 2.2990233	best: 2.2990233 (30)	total: 477ms	remaining: 14.9s
31:	learn: 2.3234601	test: 2.2958334	best: 2.2958334 (31)	total: 490ms	remaining: 14.8s
32:	learn: 2.3157980	test: 2.2910197	best: 2.2910197 (32)	total: 502ms	remaining: 14.7s
33:	learn: 2.3097993	test: 2.2870322	best: 2.2870322 (33)	total: 515ms	remaining: 14.6s
34:	learn: 2.3027111	test: 2.2847825	best: 2.2847825 (34)	total: 529ms	remaining: 14.6s
35:	learn: 2.2957806	test: 2.2869220	best: 2.2847825 (34)	total: 544ms	remaining: 14.6s
36:	learn: 2.2903928	test: 2.2844626	best: 2.2844626 (36)	total: 560ms	remaining: 14.6s
37:	learn: 2.2846003	test: 2.2823376	best: 2.2823376 (37)	total: 576ms	remaining: 14.6s
38:	learn: 2.2787740	test: 2.2854718	best: 2.2823376 (37)	total: 591ms	remaining: 14.6s
39:	learn: 2.2738772	test: 2.2835177	best: 2.2823376 (37)	total: 607ms	remaining: 14.6s
40:	learn: 2.2687621	test: 2.2815609	best: 2.2815609 (40)	total: 624ms	remaining: 14.6s
41:	learn: 2.2647582	test: 2.2790100	best: 2.2790100 (41)	total: 640ms	remaining: 14.6s
42:	learn: 2.2592172	test: 2.2817448	best: 2.2790100 (41)	total: 655ms	remaining: 14.6s
43:	learn: 2.2547602	test: 2.2815320	best: 2.2790100 (41)	total: 671ms	remaining: 14.6s
44:	learn: 2.2502000	test: 2.2804952	best: 2.2790100 (41)	total: 687ms	remaining: 14.6s
45:	learn: 2.2459314	test: 2.2811748	best: 2.2790100 (41)	total: 703ms	remaining: 14.6s
46:	learn: 2.2414419	test: 2.2840264	best: 2.2790100 (41)	total: 719ms	remaining: 14.6s
47:	learn: 2.2382062	test: 2.2821591	best: 2.2790100 (41)	total: 734ms	remaining: 14.6s
48:	learn: 2.2345420	test: 2.2803259	best: 2.2790100 (41)	total: 750ms	remaining: 14.6s
49:	learn: 2.2314673	test: 2.2789832	best: 2.2789832 (49)	total: 766ms	remaining: 14.6s
50:	learn: 2.2280802	test: 2.2781564	best: 2.2781564 (50)	total: 781ms	remaining: 14.5s
51:	learn: 2.2240826	test: 2.2778497	best: 2.2778497 (51)	total: 797ms	remaining: 14.5s
52:	learn: 2.2209830	test: 2.2762677	best: 2.2762677 (52)	total: 815ms	remaining: 14.6s
53:	learn: 2.2176226	test: 2.2805706	best: 2.2762677 (52)	total: 831ms	remaining: 14.6s
54:	learn: 2.2147801	test: 2.2797206	best: 2.2762677 (52)	total: 847ms	remaining: 14.6s
55:	learn: 2.2120725	test: 2.2782635	best: 2.2762677 (52)	total: 863ms	remaining: 14.5s
56:	learn: 2.2099465	test: 2.2767326	best: 2.2762677 (52)	total: 879ms	remaining: 14.5s
57:	learn: 2.2076161	test: 2.2762252	best: 2.2762252 (57)	total: 892ms	remaining: 14.5s
58:	learn: 2.2037946	test: 2.2806686	best: 2.2762252 (57)	total: 908ms	remaining: 14.5s
59:	learn: 2.2012737	test: 2.2793527	best: 2.2762252 (57)	total: 925ms	remaining: 14.5s
60:	learn: 2.1992408	test: 2.2784656	best: 2.2762252 (57)	total: 939ms	remaining: 14.5s
61:	learn: 2.1971079	test: 2.2774719	best: 2.2762252 (57)	total: 956ms	remaining: 14.5s
62:	learn: 2.1934728	test: 2.2766444	best: 2.2762252 (57)	total: 971ms	remaining: 14.4s
63:	learn: 2.1901668	test: 2.2751470	best: 2.2751470 (63)	total: 985ms	remaining: 14.4s
64:	learn: 2.1884626	test: 2.2743040	best: 2.2743040 (64)	total: 998ms	remaining: 14.4s
65:	learn: 2.1867985	test: 2.2731377	best: 2.2731377 (65)	total: 1.01s	remaining: 14.3s
66:	learn: 2.1845319	test: 2.2726866	best: 2.2726866 (66)	total: 1.03s	remaining: 14.3s
67:	learn: 2.1828681	test: 2.2723585	best: 2.2723585 (67)	total: 1.04s	remaining: 14.3s
68:	learn: 2.1797313	test: 2.2715251	best: 2.2715251 (68)	total: 1.06s	remaining: 14.3s
69:	learn: 2.1781798	test: 2.2711826	best: 2.2711826 (69)	total: 1.07s	remaining: 14.3s
70:	learn: 2.1755559	test: 2.2702163	best: 2.2702163 (70)	total: 1.09s	remaining: 14.2s
71:	learn: 2.1729970	test: 2.2687617	best: 2.2687617 (71)	total: 1.1s	remaining: 14.2s
72:	learn: 2.1710793	test: 2.2685107	best: 2.2685107 (72)	total: 1.12s	remaining: 14.2s
73:	learn: 2.1696591	test: 2.2672814	best: 2.2672814 (73)	total: 1.13s	remaining: 14.2s
74:	learn: 2.1683984	test: 2.2664879	best: 2.2664879 (74)	total: 1.15s	remaining: 14.2s
75:	learn: 2.1668937	test: 2.2657045	best: 2.2657045 (75)	total: 1.18s	remaining: 14.3s
76:	learn: 2.1647347	test: 2.2675731	best: 2.2657045 (75)	total: 1.2s	remaining: 14.3s
77:	learn: 2.1631993	test: 2.2672850	best: 2.2657045 (75)	total: 1.22s	remaining: 14.4s
78:	learn: 2.1613012	test: 2.2673216	best: 2.2657045 (75)	total: 1.24s	remaining: 14.4s
79:	learn: 2.1602750	test: 2.2669194	best: 2.2657045 (75)	total: 1.25s	remaining: 14.4s
80:	learn: 2.1581446	test: 2.2714447	best: 2.2657045 (75)	total: 1.27s	remaining: 14.4s
81:	learn: 2.1569663	test: 2.2712035	best: 2.2657045 (75)	total: 1.32s	remaining: 14.8s
82:	learn: 2.1558685	test: 2.2708920	best: 2.2657045 (75)	total: 1.34s	remaining: 14.8s
83:	learn: 2.1538445	test: 2.2703875	best: 2.2657045 (75)	total: 1.35s	remaining: 14.8s
84:	learn: 2.1523425	test: 2.2701956	best: 2.2657045 (75)	total: 1.37s	remaining: 14.8s
85:	learn: 2.1513312	test: 2.2696391	best: 2.2657045 (75)	total: 1.39s	remaining: 14.7s
86:	learn: 2.1502220	test: 2.2690895	best: 2.2657045 (75)	total: 1.4s	remaining: 14.7s
87:	learn: 2.1486730	test: 2.2691739	best: 2.2657045 (75)	total: 1.42s	remaining: 14.7s
88:	learn: 2.1462555	test: 2.2686892	best: 2.2657045 (75)	total: 1.43s	remaining: 14.7s
89:	learn: 2.1454956	test: 2.2681833	best: 2.2657045 (75)	total: 1.45s	remaining: 14.6s
90:	learn: 2.1441131	test: 2.2675959	best: 2.2657045 (75)	total: 1.46s	remaining: 14.6s
91:	learn: 2.1419562	test: 2.2700149	best: 2.2657045 (75)	total: 1.47s	remaining: 14.6s
92:	learn: 2.1411883	test: 2.2700068	best: 2.2657045 (75)	total: 1.49s	remaining: 14.5s
93:	learn: 2.1391919	test: 2.2693697	best: 2.2657045 (75)	total: 1.51s	remaining: 14.5s
94:	learn: 2.1381880	test: 2.2702674	best: 2.2657045 (75)	total: 1.52s	remaining: 14.5s
95:	learn: 2.1366500	test: 2.2699492	best: 2.2657045 (75)	total: 1.53s	remaining: 14.4s
96:	learn: 2.1347972	test: 2.2693374	best: 2.2657045 (75)	total: 1.55s	remaining: 14.4s
97:	learn: 2.1341137	test: 2.2691667	best: 2.2657045 (75)	total: 1.56s	remaining: 14.4s
98:	learn: 2.1333431	test: 2.2685897	best: 2.2657045 (75)	total: 1.58s	remaining: 14.4s
99:	learn: 2.1319821	test: 2.2676239	best: 2.2657045 (75)	total: 1.59s	remaining: 14.3s
100:	learn: 2.1310418	test: 2.2673908	best: 2.2657045 (75)	total: 1.6s	remaining: 14.3s
101:	learn: 2.1302520	test: 2.2674903	best: 2.2657045 (75)	total: 1.61s	remaining: 14.2s
102:	learn: 2.1292048	test: 2.2667568	best: 2.2657045 (75)	total: 1.63s	remaining: 14.2s
103:	learn: 2.1277914	test: 2.2640402	best: 2.2640402 (103)	total: 1.64s	remaining: 14.1s
104:	learn: 2.1266718	test: 2.2640102	best: 2.2640102 (104)	total: 1.65s	remaining: 14.1s
105:	learn: 2.1259348	test: 2.2641315	best: 2.2640102 (104)	total: 1.66s	remaining: 14s
106:	learn: 2.1248218	test: 2.2635817	best: 2.2635817 (106)	total: 1.68s	remaining: 14s
107:	learn: 2.1240257	test: 2.2632319	best: 2.2632319 (107)	total: 1.7s	remaining: 14s
108:	learn: 2.1223688	test: 2.2628226	best: 2.2628226 (108)	total: 1.71s	remaining: 14s
109:	learn: 2.1214908	test: 2.2627912	best: 2.2627912 (109)	total: 1.72s	remaining: 14s
110:	learn: 2.1207950	test: 2.2626240	best: 2.2626240 (110)	total: 1.74s	remaining: 13.9s
111:	learn: 2.1200014	test: 2.2618652	best: 2.2618652 (111)	total: 1.75s	remaining: 13.9s
112:	learn: 2.1193013	test: 2.2615647	best: 2.2615647 (112)	total: 1.77s	remaining: 13.9s
113:	learn: 2.1188456	test: 2.2617050	best: 2.2615647 (112)	total: 1.78s	remaining: 13.9s
114:	learn: 2.1179067	test: 2.2616954	best: 2.2615647 (112)	total: 1.8s	remaining: 13.9s
115:	learn: 2.1167731	test: 2.2604695	best: 2.2604695 (115)	total: 1.81s	remaining: 13.8s
116:	learn: 2.1160995	test: 2.2594313	best: 2.2594313 (116)	total: 1.83s	remaining: 13.8s
117:	learn: 2.1155286	test: 2.2594414	best: 2.2594313 (116)	total: 1.84s	remaining: 13.8s
118:	learn: 2.1147743	test: 2.2583736	best: 2.2583736 (118)	total: 1.86s	remaining: 13.8s
119:	learn: 2.1133448	test: 2.2594890	best: 2.2583736 (118)	total: 1.88s	remaining: 13.8s
120:	learn: 2.1129746	test: 2.2592252	best: 2.2583736 (118)	total: 1.89s	remaining: 13.7s
121:	learn: 2.1125202	test: 2.2590648	best: 2.2583736 (118)	total: 1.91s	remaining: 13.7s
122:	learn: 2.1114816	test: 2.2600797	best: 2.2583736 (118)	total: 1.92s	remaining: 13.7s
123:	learn: 2.1097918	test: 2.2599878	best: 2.2583736 (118)	total: 1.93s	remaining: 13.7s
124:	learn: 2.1082911	test: 2.2597463	best: 2.2583736 (118)	total: 1.95s	remaining: 13.6s
125:	learn: 2.1078871	test: 2.2597392	best: 2.2583736 (118)	total: 1.96s	remaining: 13.6s
126:	learn: 2.1072005	test: 2.2594129	best: 2.2583736 (118)	total: 1.97s	remaining: 13.6s
127:	learn: 2.1054724	test: 2.2595511	best: 2.2583736 (118)	total: 1.98s	remaining: 13.5s
128:	learn: 2.1040109	test: 2.2636758	best: 2.2583736 (118)	total: 2s	remaining: 13.5s
129:	learn: 2.1032242	test: 2.2627509	best: 2.2583736 (118)	total: 2.01s	remaining: 13.5s
130:	learn: 2.1029136	test: 2.2626235	best: 2.2583736 (118)	total: 2.02s	remaining: 13.4s
131:	learn: 2.1020768	test: 2.2623937	best: 2.2583736 (118)	total: 2.04s	remaining: 13.4s
132:	learn: 2.1000570	test: 2.2603577	best: 2.2583736 (118)	total: 2.05s	remaining: 13.3s
133:	learn: 2.0995019	test: 2.2605601	best: 2.2583736 (118)	total: 2.06s	remaining: 13.3s
134:	learn: 2.0982761	test: 2.2604247	best: 2.2583736 (118)	total: 2.07s	remaining: 13.3s
135:	learn: 2.0964143	test: 2.2616162	best: 2.2583736 (118)	total: 2.08s	remaining: 13.2s
136:	learn: 2.0960481	test: 2.2614119	best: 2.2583736 (118)	total: 2.1s	remaining: 13.2s
137:	learn: 2.0945484	test: 2.2608000	best: 2.2583736 (118)	total: 2.11s	remaining: 13.2s
138:	learn: 2.0939990	test: 2.2607624	best: 2.2583736 (118)	total: 2.12s	remaining: 13.2s
139:	learn: 2.0936454	test: 2.2608162	best: 2.2583736 (118)	total: 2.13s	remaining: 13.1s
140:	learn: 2.0913422	test: 2.2648307	best: 2.2583736 (118)	total: 2.15s	remaining: 13.1s
141:	learn: 2.0903261	test: 2.2648613	best: 2.2583736 (118)	total: 2.16s	remaining: 13s
142:	learn: 2.0894194	test: 2.2646849	best: 2.2583736 (118)	total: 2.17s	remaining: 13s
143:	learn: 2.0889185	test: 2.2647158	best: 2.2583736 (118)	total: 2.18s	remaining: 13s
144:	learn: 2.0886106	test: 2.2642993	best: 2.2583736 (118)	total: 2.2s	remaining: 12.9s
145:	learn: 2.0882458	test: 2.2641903	best: 2.2583736 (118)	total: 2.21s	remaining: 12.9s
146:	learn: 2.0874858	test: 2.2640514	best: 2.2583736 (118)	total: 2.22s	remaining: 12.9s
147:	learn: 2.0871267	test: 2.2637038	best: 2.2583736 (118)	total: 2.23s	remaining: 12.9s
148:	learn: 2.0863101	test: 2.2639354	best: 2.2583736 (118)	total: 2.25s	remaining: 12.8s
149:	learn: 2.0851473	test: 2.2649944	best: 2.2583736 (118)	total: 2.26s	remaining: 12.8s
150:	learn: 2.0844131	test: 2.2650496	best: 2.2583736 (118)	total: 2.27s	remaining: 12.8s
151:	learn: 2.0838608	test: 2.2636538	best: 2.2583736 (118)	total: 2.29s	remaining: 12.8s
152:	learn: 2.0832250	test: 2.2631563	best: 2.2583736 (118)	total: 2.3s	remaining: 12.7s
153:	learn: 2.0820780	test: 2.2624361	best: 2.2583736 (118)	total: 2.31s	remaining: 12.7s
154:	learn: 2.0817038	test: 2.2621365	best: 2.2583736 (118)	total: 2.32s	remaining: 12.7s
155:	learn: 2.0808482	test: 2.2612291	best: 2.2583736 (118)	total: 2.33s	remaining: 12.6s
156:	learn: 2.0801438	test: 2.2609147	best: 2.2583736 (118)	total: 2.35s	remaining: 12.6s
157:	learn: 2.0792325	test: 2.2603057	best: 2.2583736 (118)	total: 2.36s	remaining: 12.6s
158:	learn: 2.0787256	test: 2.2599550	best: 2.2583736 (118)	total: 2.37s	remaining: 12.5s
159:	learn: 2.0777353	test: 2.2601072	best: 2.2583736 (118)	total: 2.38s	remaining: 12.5s
160:	learn: 2.0761555	test: 2.2613659	best: 2.2583736 (118)	total: 2.39s	remaining: 12.5s
161:	learn: 2.0758298	test: 2.2616004	best: 2.2583736 (118)	total: 2.4s	remaining: 12.4s
162:	learn: 2.0748776	test: 2.2614277	best: 2.2583736 (118)	total: 2.42s	remaining: 12.4s
163:	learn: 2.0728404	test: 2.2629329	best: 2.2583736 (118)	total: 2.43s	remaining: 12.4s
164:	learn: 2.0723388	test: 2.2627060	best: 2.2583736 (118)	total: 2.44s	remaining: 12.4s
165:	learn: 2.0711442	test: 2.2625941	best: 2.2583736 (118)	total: 2.46s	remaining: 12.4s
166:	learn: 2.0698868	test: 2.2661506	best: 2.2583736 (118)	total: 2.48s	remaining: 12.4s
167:	learn: 2.0690292	test: 2.2644074	best: 2.2583736 (118)	total: 2.5s	remaining: 12.4s
168:	learn: 2.0671862	test: 2.2653531	best: 2.2583736 (118)	total: 2.52s	remaining: 12.4s
169:	learn: 2.0664903	test: 2.2653676	best: 2.2583736 (118)	total: 2.54s	remaining: 12.4s
170:	learn: 2.0655952	test: 2.2652263	best: 2.2583736 (118)	total: 2.56s	remaining: 12.4s
171:	learn: 2.0643747	test: 2.2651497	best: 2.2583736 (118)	total: 2.59s	remaining: 12.5s
172:	learn: 2.0639804	test: 2.2652725	best: 2.2583736 (118)	total: 2.6s	remaining: 12.5s
173:	learn: 2.0633885	test: 2.2650782	best: 2.2583736 (118)	total: 2.63s	remaining: 12.5s
174:	learn: 2.0626765	test: 2.2662897	best: 2.2583736 (118)	total: 2.64s	remaining: 12.5s
175:	learn: 2.0618733	test: 2.2663531	best: 2.2583736 (118)	total: 2.67s	remaining: 12.5s
176:	learn: 2.0615618	test: 2.2660828	best: 2.2583736 (118)	total: 2.69s	remaining: 12.5s
177:	learn: 2.0610048	test: 2.2665719	best: 2.2583736 (118)	total: 2.7s	remaining: 12.5s
178:	learn: 2.0601513	test: 2.2670792	best: 2.2583736 (118)	total: 2.73s	remaining: 12.5s
179:	learn: 2.0585436	test: 2.2653443	best: 2.2583736 (118)	total: 2.75s	remaining: 12.5s
180:	learn: 2.0569116	test: 2.2641432	best: 2.2583736 (118)	total: 2.76s	remaining: 12.5s
181:	learn: 2.0562221	test: 2.2641199	best: 2.2583736 (118)	total: 2.77s	remaining: 12.5s
182:	learn: 2.0559275	test: 2.2639733	best: 2.2583736 (118)	total: 2.79s	remaining: 12.4s
183:	learn: 2.0555241	test: 2.2637090	best: 2.2583736 (118)	total: 2.8s	remaining: 12.4s
184:	learn: 2.0549177	test: 2.2657216	best: 2.2583736 (118)	total: 2.81s	remaining: 12.4s
185:	learn: 2.0541959	test: 2.2641276	best: 2.2583736 (118)	total: 2.82s	remaining: 12.4s
186:	learn: 2.0527959	test: 2.2630768	best: 2.2583736 (118)	total: 2.84s	remaining: 12.3s
187:	learn: 2.0520708	test: 2.2630027	best: 2.2583736 (118)	total: 2.85s	remaining: 12.3s
188:	learn: 2.0508228	test: 2.2629206	best: 2.2583736 (118)	total: 2.86s	remaining: 12.3s
189:	learn: 2.0502378	test: 2.2625918	best: 2.2583736 (118)	total: 2.87s	remaining: 12.3s
190:	learn: 2.0495220	test: 2.2627425	best: 2.2583736 (118)	total: 2.89s	remaining: 12.2s
191:	learn: 2.0484702	test: 2.2629512	best: 2.2583736 (118)	total: 2.9s	remaining: 12.2s
192:	learn: 2.0481594	test: 2.2626057	best: 2.2583736 (118)	total: 2.91s	remaining: 12.2s
193:	learn: 2.0475755	test: 2.2624996	best: 2.2583736 (118)	total: 2.93s	remaining: 12.2s
194:	learn: 2.0472540	test: 2.2622687	best: 2.2583736 (118)	total: 2.94s	remaining: 12.1s
195:	learn: 2.0467318	test: 2.2623388	best: 2.2583736 (118)	total: 2.95s	remaining: 12.1s
196:	learn: 2.0462393	test: 2.2619302	best: 2.2583736 (118)	total: 2.96s	remaining: 12.1s
197:	learn: 2.0458932	test: 2.2618805	best: 2.2583736 (118)	total: 2.98s	remaining: 12.1s
198:	learn: 2.0454318	test: 2.2592054	best: 2.2583736 (118)	total: 2.99s	remaining: 12s
199:	learn: 2.0440523	test: 2.2585667	best: 2.2583736 (118)	total: 3s	remaining: 12s
200:	learn: 2.0437876	test: 2.2582722	best: 2.2582722 (200)	total: 3.01s	remaining: 12s
201:	learn: 2.0431891	test: 2.2580271	best: 2.2580271 (201)	total: 3.03s	remaining: 12s
202:	learn: 2.0424953	test: 2.2588208	best: 2.2580271 (201)	total: 3.04s	remaining: 11.9s
203:	learn: 2.0418974	test: 2.2589694	best: 2.2580271 (201)	total: 3.05s	remaining: 11.9s
204:	learn: 2.0414994	test: 2.2585836	best: 2.2580271 (201)	total: 3.06s	remaining: 11.9s
205:	learn: 2.0409922	test: 2.2582708	best: 2.2580271 (201)	total: 3.08s	remaining: 11.9s
206:	learn: 2.0405963	test: 2.2582276	best: 2.2580271 (201)	total: 3.09s	remaining: 11.8s
207:	learn: 2.0400225	test: 2.2583730	best: 2.2580271 (201)	total: 3.1s	remaining: 11.8s
208:	learn: 2.0395728	test: 2.2577818	best: 2.2577818 (208)	total: 3.11s	remaining: 11.8s
209:	learn: 2.0385996	test: 2.2586369	best: 2.2577818 (208)	total: 3.12s	remaining: 11.8s
210:	learn: 2.0379987	test: 2.2580595	best: 2.2577818 (208)	total: 3.13s	remaining: 11.7s
211:	learn: 2.0366967	test: 2.2606285	best: 2.2577818 (208)	total: 3.15s	remaining: 11.7s
212:	learn: 2.0358867	test: 2.2608644	best: 2.2577818 (208)	total: 3.16s	remaining: 11.7s
213:	learn: 2.0353509	test: 2.2609621	best: 2.2577818 (208)	total: 3.18s	remaining: 11.7s
214:	learn: 2.0341490	test: 2.2609545	best: 2.2577818 (208)	total: 3.19s	remaining: 11.6s
215:	learn: 2.0331597	test: 2.2606336	best: 2.2577818 (208)	total: 3.2s	remaining: 11.6s
216:	learn: 2.0325606	test: 2.2598559	best: 2.2577818 (208)	total: 3.21s	remaining: 11.6s
217:	learn: 2.0319364	test: 2.2599314	best: 2.2577818 (208)	total: 3.22s	remaining: 11.6s
218:	learn: 2.0312829	test: 2.2591936	best: 2.2577818 (208)	total: 3.24s	remaining: 11.5s
219:	learn: 2.0304896	test: 2.2592326	best: 2.2577818 (208)	total: 3.25s	remaining: 11.5s
220:	learn: 2.0302537	test: 2.2589423	best: 2.2577818 (208)	total: 3.26s	remaining: 11.5s
221:	learn: 2.0298993	test: 2.2586892	best: 2.2577818 (208)	total: 3.27s	remaining: 11.5s
222:	learn: 2.0297031	test: 2.2584321	best: 2.2577818 (208)	total: 3.28s	remaining: 11.4s
223:	learn: 2.0289324	test: 2.2572840	best: 2.2572840 (223)	total: 3.29s	remaining: 11.4s
224:	learn: 2.0283895	test: 2.2574599	best: 2.2572840 (223)	total: 3.3s	remaining: 11.4s

CatBoostRegressor(depth=8, learning_rate=0.03, loss_function='RMSE')

In [280]:
pred = model.predict(X_test)

In [281]:
f = open("ans2.csv", 'w')

f.write("row_id,demand\n")

for i, p in enumerate(pred):
    f.write(str(ids[i]) + "," + str(p) + '\n')
f.close()